version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    registries: "*"
    allow:
      - dependency-type: "all"
    groups:
      agp-major:
        patterns: [ com.android.application, com.android.library ]
        update-types: [ major ]
      agp-minor:
        patterns: [ com.android.application, com.android.library ]
        update-types: [ minor ]
      agp-patch:
        patterns: [ com.android.application, com.android.library ]
        update-types: [ patch ]
registries:
  maven-google:
    type: "maven-repository"
    url: "https://maven.google.com"
    replaces-base: true
