[versions]
agp = "8.5.0-alpha06"
kotlin = "1.9.23"

[libraries]
junit = "junit:junit:4.13.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
