[versions]
agp = "8.3.0"
kotlin = "1.9.22"

[libraries]
junit = "junit:junit:4.13.2"

# Fake agp libraries to detect new versions
gradle-8_2 = { module = "com.android.tools.build:gradle", version = "8.2.2" }
gradle-8_3 = { module = "com.android.tools.build:gradle", version = "8.3.0-rc02" }
gradle-8_4 = { module = "com.android.tools.build:gradle", version = "8.4.0-alpha10" }
gradle-8_5 = { module = "com.android.tools.build:gradle", version = "8.5.0-alpha01" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
