name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        agp: [ 8.3.1, '' ]
      fail-fast: false
    name: "AGP ${{ matrix.agp || 'default' }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
          add-job-summary-as-pr-comment: on-failure
      - uses: gradle/actions/wrapper-validation@v3
      - run: ./gradlew -Pagp=${{ matrix.agp }} build --continue
