name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  configure-agp-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "matrix=$(grep --perl-regexp --only-matching 'gha-agp-\w+\s*=\s*\K.+' gradle/libs.versions.toml | jq --null-input --compact-output '[inputs | sub(".+:"; "")] | {agp:.}')" >> "$GITHUB_OUTPUT"

  ci:
    runs-on: ubuntu-latest
    needs: configure-agp-matrix
    strategy:
      matrix: ${{ fromJson(needs.configure-agp-matrix.outputs.matrix) }}
      fail-fast: false
    name: "AGP ${{ matrix.agp || 'default' }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: true
          gradle-home-cache-cleanup: true
          add-job-summary-as-pr-comment: on-failure
      - run: ./gradlew -Pagp=${{ matrix.agp }} build --continue
